[id] # schema/master/id.toml
  [id.Id]
    name  = "Id"
    begin = 1
    end   = 9999
  [id.Title]
    name  = "Title"
    begin = 10001
    end   = 19999
  [id.CopyRight]
    name  = "CopyRight"
    begin = 20001
    end   = 29999
